Update nokogiri gem when installing deface-based plugins
deface < 1.0 has a dependency on ~> 1.5.0 which conflicts
with the 1.6.x gem installed by default in core.

diff --git a/plugins/ruby-foreman-column-view/debian/postinst b/plugins/ruby-foreman-column-view/debian/postinst
--- a/plugins/ruby-foreman-column-view/debian/postinst
+++ b/plugins/ruby-foreman-column-view/debian/postinst
@@ -19,9 +19,14 @@ trap db_stop EXIT
 
 # Update gems
 cd /usr/share/foreman
+# Nokogiri causes us pain due to tight dependencies within deface
+# so update it first. We rescue it as trusty will return non-zero if
+# nokogiri isn't in the Gemfile.
 if [ ! -z "${DEBUG}" ]; then
+  bundle update nokogiri || true
   bundle update foreman_column_view
 else
+  bundle update nokogiri 2>&1 >> $LOGFILE || true
   bundle update foreman_column_view 2>&1 >> $LOGFILE
 fi
 
diff --git a/plugins/ruby-foreman-setup/debian/postinst b/plugins/ruby-foreman-setup/debian/postinst
--- a/plugins/ruby-foreman-setup/debian/postinst
+++ b/plugins/ruby-foreman-setup/debian/postinst
@@ -20,13 +20,18 @@ trap db_stop EXIT
 
 # Update gems
 cd /usr/share/foreman
+# Nokogiri causes us pain due to tight dependencies within deface
+# so update it first. We rescue it as trusty will return non-zero if
+# nokogiri isn't in the Gemfile.
 if [ ! -z "${DEBUG}" ]; then
+  bundle update nokogiri || true
   if bundle show $PLUGIN >/dev/null 2>&1; then
     bundle update $PLUGIN
   else
     bundle install
   fi
 else
+  bundle update nokogiri 2>&1 >> $LOGFILE || true
   if bundle show $PLUGIN >/dev/null 2>&1; then
     bundle update $PLUGIN 2>&1 >> $LOGFILE
   else
